### ISSUE TITLE
tool-dlls for win32 cannot be built as download is missing

### ISSUE THREAD

**Issue by Leseratte10** [devkitPro/tool-packages#1]
The download link for the 32-bit version of tool-dlls added in a619d6e5fc (https://github.com/devkitPro/buildscripts/releases/download/support-files/tool32-dlls-1.0.tar.xz) is unreachable and thus this package cannot be built.

**Comment by WinterMute** [comment]
You don't need to build it, why are you trying to build things from this repo?

**Comment by Leseratte10** [comment]
I don't "need" to build it, that is correct. Thanks for fixing the missing link.

**Comment by WinterMute** [comment]
> I don't "need" to build it, that is correct. Thanks for fixing the missing link.

Why are you trying to build it at all? You have zero need to make packages from this repo.
