### ISSUE TITLE
What is this repository used for?

### ISSUE THREAD

**Issue by leonardoInf** [devkitPro/tool-packages#4]
@WinterMute you are saying in this issue https://github.com/devkitPro/tool-packages/issues/1 that you do not want people to create arch packages from this repository and I can understand why. Allowing people to do so could encourage them to distribute binaries which you do not want.
Furthermore I see some flaws in this repository (e.g. devkit links are broken) but I am not sure if you will fix this. Nonetheless you are maintaining this repository. 
So what exactly is the purpose of it? 

PS: You did not provide a license for this repository. Could you clarify this please?

**Comment by WinterMute** [comment]
For various reasons relating to "scene" toxicity I don't particularly want to discuss this here. You should be able to find a means to contact me privately, please do.
